services:

  backend_kafe_ternak:

    build:

      context: .

      dockerfile: Dockerfile

    image: localhost/backend_kafe_ternak:latest

    container_name: backend_kafe_ternak

    restart: unless-stopped

    ports:

      - "8005:8000"

    working_dir: /app

    env_file:

      - .env

    volumes:

      - .:/app:z

    command: python3 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 2